"""Capture the query plan for every PostgreSQL query, on both models.

    docker exec pg-client python -m bench.explain            > docs/postgres-plans.txt
    docker exec pg-client python -m bench.explain --only q6

`docs/schema-comparison.md §6` lists "query 6's cause is inferred, not
confirmed — no query plan was captured" as a limitation, because neither
Oracle NoSQL CE nor FoundationDB will show one: kvlite exposes no `EXPLAIN`
through the HTTP proxy, and FoundationDB has no planner at all — the access
path is whatever the client code reads. PostgreSQL does have one, and telling
it apart from a guess is worth a tool.

The plans are what turn a latency into an explanation. They are the evidence
for the claim that a given query used a given index, and for the more
interesting claim that PostgreSQL solved query 6's ordering problem in a third
way — neither FoundationDB's order-in-the-key nor Oracle NoSQL's sort.

Implementation note: rather than repeating the twenty SQL statements here,
where they would drift out of step with the ones actually benchmarked, this
runs the real `PostgresBackend` methods with the execute path swapped for
`EXPLAIN (ANALYZE, ...)`. What is explained is therefore exactly what is
measured, by construction. The methods' return values are meaningless under
this swap and are discarded.
"""

from __future__ import annotations

import argparse
import sys

from bench.harness import QUERIES
from bench.queries import PostgresBackend

EXPLAIN = "EXPLAIN (ANALYZE, VERBOSE off, COSTS off, BUFFERS, TIMING on) "


class ExplainBackend(PostgresBackend):
    """PostgresBackend with every statement routed through EXPLAIN ANALYZE."""

    def __init__(self):
        super().__init__()
        self.captured: list[tuple[str, str]] = []

    def rows(self, statement: str, params: tuple = ()):
        with self.conn.cursor() as cur:
            cur.execute(EXPLAIN + statement, params)
            plan = "\n".join(row[0] for row in cur.fetchall())
        self.captured.append((" ".join(statement.split()), plan))
        return []

    def scalar(self, statement: str, params: tuple = ()):
        self.rows(statement, params)
        return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="EXPLAIN ANALYZE every query.")
    parser.add_argument("--only", help="comma-separated query ids, e.g. q6,q8")
    args = parser.parse_args(argv)
    wanted = set(args.only.split(",")) if args.only else None

    backend = ExplainBackend()
    print("# PostgreSQL query plans")
    print(f"# server_version {backend.server_version}")
    print("#")
    print("# Generated by `python -m bench.explain`. Each plan is EXPLAIN ANALYZE")
    print("# of the statement bench/queries.py actually benchmarks.\n")

    try:
        for qid, category, description, _, _ in QUERIES:
            if wanted and qid not in wanted:
                continue
            print(f"\n{'=' * 78}\n{qid.upper()}  {description}  [{category}]\n{'=' * 78}")
            for model in ("l1", "l2"):
                backend.captured.clear()
                backend.run(model, qid)
                for statement, plan in backend.captured:
                    print(f"\n-- {model.upper()}")
                    print(f"   {statement}\n")
                    for line in plan.splitlines():
                        print(f"   {line}")
    finally:
        backend.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
